### ISSUE TITLE
Window not rendering

### ISSUE THREAD

**Issue by felipekm** [jeanlivino/whatsapp-link-generator#3]
Trying to access the generated link: http://wpp-redirect.herokuapp.com/go/?p=5551996141854&m=teste

It is rendering a raw html:

![image](https://user-images.githubusercontent.com/205932/58177510-e5840680-7c7a-11e9-9579-29bae6f5768b.png)

**Comment by iileandro** [comment]
On Firefox and EDGE it's OK.

**Comment by iileandro** [comment]
It's some "Web WhatsApp" Issue. I tried to contact them on twitter and facebook.

**Comment by jeanlivino** [comment]
Its a issue from WhatsApp and not the application. I try on linux and works.

**Comment by felipekm** [comment]
They already fixed! Thanks
