### ISSUE TITLE
On Chrome getting HTML Source Code

### ISSUE THREAD

**Issue by iileandro** [jeanlivino/whatsapp-link-generator#4]
https://web.whatsapp.com/send?phone=558699999999&text=aaaaaa

on chrome not working for me. How is it now for you?

**Comment by iileandro** [comment]
I know the problem isn't your api. WhatApp issue.

**Comment by alande-amorim** [comment]
This happens to me also. If you try to access the generated URL (https://web.whatsapp.com/send?phone=PHONE_NUMBER&text=TEXT) on Linux the browser forces you to download the source code.

**Comment by jeanlivino** [comment]
Thank you @alande-amorim, i am closing this issue
